### ISSUE TITLE
Main 报错,

### ISSUE THREAD

**Issue by Redlove2015** [ronething/xiudong-selenium#23]
C:\Users\Ronaldo\PycharmProjects\xiudong-selenium\venv\Scripts\python.exe C:/Users/Ronaldo/PycharmProjects/xiudong-selenium/main.py
Traceback (most recent call last):
  File "C:\Users\Ronaldo\PycharmProjects\xiudong-selenium\venv\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Ronaldo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Ronaldo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ronaldo\PycharmProjects\xiudong-selenium\main.py", line 8, in <module>
    driver = load_driver()
  File "C:\Users\Ronaldo\PycharmProjects\xiudong-selenium\driver.py", line 31, in load_driver
    driver = webdriver.Chrome(executable_path=executable_path, options=options)
  File "C:\Users\Ronaldo\PycharmProjects\xiudong-selenium\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Ronaldo\PycharmProjects\xiudong-selenium\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\Ronaldo\PycharmProjects\xiudong-selenium\venv\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

Process finished with exit code 1

以下能正常执行
from selenium import webdriver
driver = webdriver.Chrome()
url = "http://www.baidu.com"
driver.get(url)

**Comment by ronething** [comment]
driver 路径需要指定对。要么复制到当前目录 chromedriver.exe，要么直接指定全路径。

https://github.com/ronething/xiudong-selenium/blob/ad1c8c88ca10d7ba6344906ca5a8e74659ba55d5/driver.py#L31
