### ISSUE TITLE
Could not call it without arguments?

### ISSUE THREAD

**Issue by ZPPengZhou** [ronething/xiudong-selenium#35]
您好，我想请教一下，以下报错可能是什么原因导致的？我看到有另外一个小伙伴也遇到了同样的问题。
```
PyDev console: starting.
Traceback (most recent call last):
  File "C:\Users\17258\Desktop\xiudong-selenium-main\venv\lib\site-packages\flask\cli.py", line 77, in find_best_app
    app = app_factory()
TypeError: create_app() missing 2 required positional arguments: 'driver' and 'pool'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "C:\Users\17258\Desktop\xiudong-selenium-main\venv\lib\site-packages\flask\cli.py", line 389, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\17258\Desktop\xiudong-selenium-main\venv\lib\site-packages\flask\cli.py", line 251, `in` locate_app
    return find_best_app(module)
  File "C:\Users\17258\Desktop\xiudong-selenium-main\venv\lib\site-packages\flask\cli.py", line 85, in find_best_app
    raise NoAppException(
flask.cli.NoAppException: Detected factory 'create_app' in module 'xiudong-selenium-main.app', but could not call it without arguments. Use "FLASK_APP='xiudong-selenium-main.app:create_app(args)'" to specify arguments.
```

**Comment by ronething** [comment]
你可以考虑终端运行 `python3 main.py` 而不是通过 flask cli 运行程序。

**Comment by ZPPengZhou** [comment]
> 你可以考虑终端运行 `python3 main.py` 而不是通过 flask cli 运行程序。

是这样的，我尝试过使用运行过`python3 main.py` 但是并没有任何反应，没有弹出浏览器，127.0.0.1:9997也不可以访问，是我漏了什么步骤吗？

**Comment by ronething** [comment]
你可以先输入 python3

看看提示什么。

**Comment by ZPPengZhou** [comment]
> 你可以先输入 python3
> 
> 看看提示什么。

弹出了一个Microsoft Store，提示我获取python3.10？

**Comment by ZPPengZhou** [comment]
> 那你输入 python 呢 不带3

这个我昨天尝试过了，昨天不行。但是刚刚又可以了，跑起来了已经，不知道为啥。
另外我还想请教一下，用python命令运行和用cli运行有什么区别？（我是学java的）

**Comment by ronething** [comment]
flack cli 应该是会找 create_app func 然后运行 不过因为我这个函数有两个入参导致产生了问题。直接 python 会运行 main 文件的那几行。（大概是这样 我也挺久没玩 flask/python 了。

**Comment by ronething** [comment]
先 close 有新问题再提 issue 谢谢
