### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by jj023721** [ronething/xiudong-selenium#59]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\xiudong-selenium-main\main.py", line 9, in <module>
    driver = load_driver()
  File "C:\Users\Administrator\Desktop\xiudong-selenium-main\driver.py", line 32, in load_driver
    driver = webdriver.Chrome(executable_path=executable_path, options=options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

但是我运行以下代码是没问题的
from selenium import webdriver

driver = webdriver.Chrome()
url = 'https://www.csdn.net/'
driver.get(url)
driver.maximize_window()

这怎么解决呀

**Comment by ronething** [comment]
refer: https://github.com/ronething/xiudong-selenium/issues/23#issuecomment-1153239551

**Comment by jj023721** [comment]
你好，这里是蒋永梁，你的邮件已收到！

**Comment by jj023721** [comment]
好的收到
